<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="./src/Shared/Props/projects.versions.props"/>
	<PropertyGroup>
		<PackageType>Template</PackageType>
		<PackageId>MtBlazorAdminTemplate</PackageId>
		<Title>MtBlazorAdminTemplate</Title>
		<Authors>MarvelTiter</Authors>
		<PackageTags>dotnet-new;templates;blazor-server;wpf;winforms</PackageTags>
		<Description>BlazorAdmin Project Template</Description>
		<TargetFramework>net8.0</TargetFramework>
		<IncludeContentInPack>true</IncludeContentInPack>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<ContentTargetFolders>content</ContentTargetFolders>
		<Version>$(MainProjectVersion)</Version>
		<NoWarn>$(NoWarn);NU5128</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="src\**\*"
		  Exclude="
    src\**\bin\**;
    src\**\obj\**;
    src\node_modules\**;
    *.lock.json;
    **\.vs\**\*;
    **\.idea\**;
    src\**\BlazorTemplates\**
    " />
		<Compile Remove="**\*" />
	</ItemGroup>

	<ItemGroup>
		<None Include=".\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
