using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace BlazorTemplate.UI.FluentUI.Generators;

/// <summary>
///     为声明为 <c>AdditionalFiles</c> 的 <c>svg-*.svg</c> 生成强类型 FluentUI <c>Icon</c> 子类。
///     <para>
///         每个 <c>svg-xxx.svg</c> 对应一个 <c>SvgXxxIcon : Icon</c>，svg 原始内容内嵌到构造函数，
///         走 FluentUI 的「继承 Icon 类」自定义图标路线（内联 svg、可上色），而非 <c>Icon.FromImageUrl</c>
///         （后者是 <c>&lt;img&gt;</c> 渲染，失去 fill 上色能力）。
///     </para>
///     <remarks>
///         本生成器是 netstandard2.0，<strong>不引用</strong> FluentUI，产物里所有 FluentUI 类型都用字符串全限定名拼写。
///         命名空间取编译程序集名，与 <c>SvgContentClassGenerator</c> 保持一致。
///         仅应挂载到 <c>BlazorTemplate.UI.FluentUI</c> 项目，勿挂到 ClientCore（否则 CS0234）。
///     </remarks>
/// </summary>
[Generator(LanguageNames.CSharp)]
public class FluentIconClassGenerator : IIncrementalGenerator
{
    private const string IconFullName = "global::Microsoft.FluentUI.AspNetCore.Components.Icon";
    private const string IconVariantFullName = "global::Microsoft.FluentUI.AspNetCore.Components.IconVariant";
    private const string IconSizeFullName = "global::Microsoft.FluentUI.AspNetCore.Components.IconSize";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var svgs = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".svg", StringComparison.OrdinalIgnoreCase))
            .Collect();

        var compilationWithSvgs = context.CompilationProvider.Combine(svgs);

        context.RegisterSourceOutput(compilationWithSvgs, static (context, result) =>
        {
            var (compilation, svgs) = result;
            var assemblyName = compilation.Assembly.Name;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine($"namespace {assemblyName};");
            sb.AppendLine();

            var icons = svgs
                .Select(static s => new { Name = Path.GetFileNameWithoutExtension(s.Path), Content = s.GetText()?.ToString() }).Distinct()
                .Where(static s => s.Name.StartsWith("svg-", StringComparison.Ordinal) && s.Content is not null).ToList();

            // 中间基类：不重写 ToMarkup（渲染走 IconSize.Custom 原样输出完整 svg），只提供 WithSize。
            // Icon.Size 是 init 只能构造时赋值，故用 WithSize 返回「同类型的新实例」——其行为是直接改写 svg 的 width/height。
            sb.AppendLine($$"""

                    public static class FluentIcons
                    {

                    """);

            foreach (var icon in icons)
            {
                var r = SvgFileParse.Utils.ProcessSvgContent(icon.Content!);
                var className = ToPascalCase(icon.Name);

                // Content 用完整 <svg> 文档（含 viewBox），而非剥离外层的 <g>——官方 issue #1328 的推荐用法。
                // 把 <svg> 开标签里的 width/height 值替换成占位符，运行时由 Resize 改写为指定尺寸。
                var svgTemplate = TemplateSvg(r.OriginalContent);
                var rawSvg = GetRawStringLiteral(svgTemplate);

                // 默认宽度来自源 svg 的 width 属性（IconSize.Custom 时用），去掉 px 等单位。
                var defaultWidth = NormalizeLength(GetAttribute(r.Attributes, "width")) ?? "24";
                var defaultWidthLiteral = ToLiteral(defaultWidth);

                sb.AppendLine($$"""
                        public static {{IconFullName}} {{className}} { get; } = new {{className}}Icon();

                        public sealed class {{className}}Icon : global::BlazorTemplate.UI.FluentUI.Components.SvgIconBase
                        {
                            private const string SvgTemplate = {{rawSvg}};
                            private const string DefaultWidth = {{defaultWidthLiteral}};

                            public {{className}}Icon() : this({{IconSizeFullName}}.Custom) { }

                            public {{className}}Icon({{IconSizeFullName}} size)
                                : base("{{icon.Name}}", Resize(SvgTemplate, size, DefaultWidth), size) { }

                            public override {{IconFullName}} WithSize({{IconSizeFullName}} size) => new {{className}}Icon(size);
                        }

                    """);
            }

            // 生成编译期字符串 -> Icon 的分发方法，供 IconHelper 按名字命中，避免运行时反射/字符串匹配。
            sb.AppendLine("    /// <summary>按图标名（含 svg- 前缀）命中对应的强类型 Icon；未命中返回 null。</summary>");
            sb.AppendLine($"    public static {IconFullName}? Get(string name)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (name)");
            sb.AppendLine("        {");
            if (icons.Count == 0)
            {
                sb.AppendLine("            default: return null;");
            }
            else
            {
                foreach (var icon in icons)
                {
                    var className = ToPascalCase(icon.Name);
                    sb.AppendLine($"            case \"{icon.Name}\": return {className};");
                }
                sb.AppendLine("            default: return null;");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            sb.AppendLine("}");
            context.AddSource("FluentIcons.g.cs", sb.ToString());
        });
    }

    /// <summary>把 "svg-home" 转成 "SvgHome"，"svg-assign_permissions" 转成 "SvgAssignPermissions"。</summary>
    private static string ToPascalCase(string name)
    {
        var parts = name.Split('-', '_');
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length == 0) continue;
            sb.Append(char.ToUpperInvariant(part[0]));
            sb.Append(part.Substring(1));
        }
        return sb.ToString();
    }

    private static string GetRawStringLiteral(string text)
    {
        string delimiter = "\"\"\"";
        return $@"
{delimiter}
{text.Trim('\r', '\n')}
{delimiter}";
    }

    /// <summary>从 svg 标签属性字典里取值（大小写不敏感）。</summary>
    private static string? GetAttribute(Dictionary<string, object> attributes, string key)
    {
        if (attributes.TryGetValue(key, out var value) && value is string s && !string.IsNullOrWhiteSpace(s))
        {
            return s;
        }
        // 属性名大小写兜底
        foreach (var kv in attributes)
        {
            if (string.Equals(kv.Key, key, StringComparison.OrdinalIgnoreCase) && kv.Value is string sv && !string.IsNullOrWhiteSpace(sv))
            {
                return sv;
            }
        }
        return null;
    }

    /// <summary>去掉长度值的单位（如 "24px" -> "24"），非数字则返回 null。</summary>
    private static string? NormalizeLength(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }
        var s = value!.Trim();
        var end = 0;
        while (end < s.Length && (char.IsDigit(s[end]) || s[end] == '.'))
        {
            end++;
        }
        if (end == 0)
        {
            return null;
        }
        return s.Substring(0, end);
    }

    /// <summary>
    /// 把完整 svg 文档的 <c>&lt;svg&gt;</c> 开标签里的 <c>width</c>/<c>height</c> 属性值替换成占位符
    /// <c>__W__</c>/<c>__H__</c>，运行时由 <c>SvgIconBase.Resize</c> 改写为指定尺寸。
    /// 只匹配属性名前有空白的 <c>width</c>/<c>height</c>（避免误伤 <c>stroke-width</c> 等）。
    /// </summary>
    private static string TemplateSvg(string originalContent)
    {
        int tagEnd = originalContent.IndexOf('>');
        if (tagEnd < 0)
        {
            return originalContent;
        }
        var openTag = originalContent.Substring(0, tagEnd + 1);
        var rest = originalContent.Substring(tagEnd + 1);
        openTag = System.Text.RegularExpressions.Regex.Replace(
            openTag,
            @"(\s)width=""[^""]*""",
            "$1width=\"__W__\"",
            System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        openTag = System.Text.RegularExpressions.Regex.Replace(
            openTag,
            @"(\s)height=""[^""]*""",
            "$1height=\"__H__\"",
            System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        return openTag + rest;
    }

    /// <summary>把字符串转成 C# 字符串字面量（转义引号/反斜杠），用于拼进 const string 字段。</summary>
    private static string ToLiteral(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\r': sb.Append("\\r"); break;
                case '\n': sb.Append("\\n"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(ch); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
