<Project Sdk="Microsoft.NET.Sdk.Web">
	<Import Project="../Shared/Props/pack.settings.props" />
	<Import Project="../Shared/Props/projects.versions.props" />
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputType Condition="'$(Configuration)'=='Debug'">Exe</OutputType>
		<OutputType Condition="'$(Configuration)'!='Debug'">WinExe</OutputType>
		<DisableWinExeOutputInference>true</DisableWinExeOutputInference>
		<IsPackable>true</IsPackable>
		<Version>$(MainProjectVersion)</Version>
	</PropertyGroup>
	
	<ItemGroup>
	  <Content Remove="Langs\zh-CN\index.json" />
	  <Content Remove="Langs\zh-CN\RouterStore.json" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Langs\zh-CN\index.json" />
	  <EmbeddedResource Include="Langs\zh-CN\RouterStore.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.10" />
		<PackageReference Include="LightORM.Providers.Sqlite" Version="2026.6.19.1" />
		<PackageReference Include="LegacyBlazorJs" Version="10.0.10.64" />
	</ItemGroup>

	<!--#if(AlwaysFalse)-->
	<ItemGroup>
		<ProjectReference Include="..\BlazorAdmin.Client\BlazorAdmin.Client.csproj" />
		<ProjectReference Include="..\Shared\BlazorTemplates\BlazorTemplate.AppCore\BlazorTemplate.AppCore.csproj" />
		<ProjectReference Include="..\Shared\BlazorTemplates\BlazorTemplate.UI.AntBlazor\BlazorTemplate.UI.AntBlazor.csproj" />
	</ItemGroup>
	<!--#endif-->
	<!--#if(UseClientProject)-->
	<ItemGroup Condition="'$(CurrentMode)'== 'Package'">
		<ProjectReference Include="..\BlazorAdmin.Client\BlazorAdmin.Client.csproj" />
		<PackageReference Include="BlazorTemplate.AppCore" Version="$(AppCoreVersion)" />
	</ItemGroup>
	<!--#endif-->
	<!--#if(!UseClientProject)-->
	<ItemGroup Condition="'$(CurrentMode)'== 'Package'">
		<PackageReference Include="BlazorTemplate.AppCore" Version="$(AppCoreVersion)" />
		<PackageReference Include="BlazorTemplate.UI.AntBlazor" Version="$(AntUIVersion)" />
	</ItemGroup>
	<!--#endif-->
	<ItemGroup>
		<Content Update="appsettings.Development.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Update="Login.razor">
		  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <None Update="simple.db">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
