using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace SvgContentClassGenerator;

[Generator(LanguageNames.CSharp)]
public class Generator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var svgs = context.AdditionalTextsProvider.Where(static file => file.Path.EndsWith(".svg", StringComparison.OrdinalIgnoreCase)).Collect();
        var compilationWithSvgs = context.CompilationProvider.Combine(svgs);
        context.RegisterSourceOutput(compilationWithSvgs, static (context, result) =>
        {
            var (compilation, svgs) = result;
            var a = compilation.Assembly.Name;
            var svgContentClass = new StringBuilder();
            svgContentClass.AppendLine("// <auto-generated />");
            svgContentClass.AppendLine($"namespace {a};");
            svgContentClass.AppendLine("public static class SvgContent");
            svgContentClass.AppendLine("{");
            
            var svgProviderClass = new StringBuilder();
            svgProviderClass.AppendLine("// <auto-generated />");
            svgProviderClass.AppendLine($"namespace {a};");
            svgProviderClass.AppendLine("public class SvgProvider: global::BlazorTemplate.ClientCore.Services.ISvgIconProvider");
            svgProviderClass.AppendLine("{");
            svgProviderClass.AppendLine("""
                    [global::System.Runtime.CompilerServices.ModuleInitializer]
                    public static void Initialize()
                    {
                        global::BlazorTemplate.ClientCore.DefaultServicesImpl.DefaultSvgIconService.RegisterIcons<SvgProvider>();
                    }
                    
                    public static IEnumerable<global::BlazorTemplate.ClientCore.Services.SvgParsingResult> GetIcons()
                    {
                """);
            foreach (var svg in svgs
            .Select(s => new {Name = Path.GetFileNameWithoutExtension(s.Path), Content = s.GetText()?.ToString() }).Distinct()
            .Where(s => s.Name.StartsWith("svg-") && s.Content is not null))
            {
                //var iconName = Path.GetFileNameWithoutExtension(svg.Path);
                //if (iconName.StartsWith("svg-") == false)
                //{
                //    continue;
                //}
                //var svgContent = svg.GetText()?.ToString();
                //if (svgContent is null)
                //{
                //    continue;
                //}
                var iconName = svg.Name;
                var svgContent = svg.Content!;
                var r = ProcessSvgContent(svgContent);
                var propName = iconName.Replace("-", "_");
                var attributesString = r.Attributes.Count > 0 ? $$"""
                new({{r.Attributes.Count}}) { {{string.Join(", ", r.Attributes.Select(kv => $"{{\"{kv.Key}\", \"{kv.Value}\"}}"))}} }
                """ : "[]";
                svgContentClass.AppendLine($$"""
                        private static Dictionary<string, object> {{propName}}_Attributes { get; } 
                            = {{attributesString}};

                        private static string {{propName}}_InnerContent { get; } 
                            = {{GetRawStringLiteral(r.InnerContent)}};

                        private static string {{propName}}_OriginalContent { get; } 
                            = {{GetRawStringLiteral(r.OriginalContent)}};

                        public static global::BlazorTemplate.ClientCore.Services.SvgParsingResult {{propName}} { get; } 
                            = new("{{iconName}}", {{propName}}_InnerContent, {{propName}}_Attributes, {{propName}}_OriginalContent);

                    """);

                svgProviderClass.AppendLine($"""
                            yield return global::{a}.SvgContent.{propName};
                    """);
            }
            svgContentClass.AppendLine("}");
            if (svgs.Length == 0)
            {
                svgProviderClass.AppendLine("        yield break;");
            }
            svgProviderClass.AppendLine("    }");
            svgProviderClass.AppendLine("}");
            context.AddSource("SvgContent.g.cs", svgContentClass.ToString());
            context.AddSource("SvgProvider.g.cs", svgProviderClass.ToString());
        });
    }

    private class SvgParsingResult
    {
        public string InnerContent { get; }
        public Dictionary<string, object> Attributes { get; }
        public string OriginalContent { get; }

        public SvgParsingResult(string innerContent, Dictionary<string, object> attributes,
                               string originalContent)
        {
            InnerContent = innerContent;
            Attributes = attributes;
            OriginalContent = originalContent;
        }
    }

    private static string GetRawStringLiteral(string text)
    {
        string delimiter = "\"\"\"";
        return $@"
{delimiter}
{text.Trim('\r', '\n')}
{delimiter}";
    }

    private static SvgParsingResult ProcessSvgContent(string content)
    {
        content = CleanSvgContent(content);
        return ParseSvgContent(content);
    }

    private static SvgParsingResult ParseSvgContent(string content)
    {
        // 查找<svg>标签
        int svgStart = content.IndexOf("<svg", StringComparison.OrdinalIgnoreCase);
        if (svgStart == -1)
        {
            return new SvgParsingResult(content, new Dictionary<string, object>(), content);
        }

        // 查找<svg>标签结束位置
        int svgTagEnd = content.IndexOf('>', svgStart);
        if (svgTagEnd == -1)
        {
            return new SvgParsingResult(content, new Dictionary<string, object>(), content);
        }

        int svgContentStart = svgTagEnd + 1;

        // 提取属性
        var attributes = ExtractSvgAttributes(content, svgStart, svgTagEnd);

        // 查找</svg>标签
        int svgEnd = content.IndexOf("</svg>", svgContentStart, StringComparison.OrdinalIgnoreCase);
        string innerContent;

        if (svgEnd == -1)
        {
            innerContent = content.Substring(svgContentStart);
        }
        else
        {
            innerContent = content.Substring(svgContentStart, svgEnd - svgContentStart);
        }

        return new SvgParsingResult(innerContent, attributes, content);
    }

    private static string CleanSvgContent(string content)
    {
        content = RemoveXmlDeclaration(content);
        content = RemoveDoctype(content);
        return content.Trim();
    }

    private static string RemoveXmlDeclaration(string content)
    {
        if (content.StartsWith("<?xml", StringComparison.OrdinalIgnoreCase))
        {
            int end = content.IndexOf("?>", StringComparison.Ordinal);
            if (end != -1)
            {
                return content.Substring(end + 2).Trim();
            }
        }
        return content;
    }

    private static string RemoveDoctype(string content)
    {
        if (content.StartsWith("<!DOCTYPE", StringComparison.OrdinalIgnoreCase))
        {
            int end = content.IndexOf('>');
            if (end != -1)
            {
                return content.Substring(end + 1).Trim();
            }
        }
        return content;
    }

    private static Dictionary<string, object> ExtractSvgAttributes(string svgTag, int start, int end)
    {
        var attributes = new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase);

        // 跳过"<svg"
        int currentPos = start + 4;

        while (currentPos < end)
        {
            // 跳过空白字符
            while (currentPos < end && char.IsWhiteSpace(svgTag[currentPos]))
            {
                currentPos++;
            }

            if (currentPos >= end) break;

            // 查找属性名
            int nameStart = currentPos;
            while (currentPos < end && !char.IsWhiteSpace(svgTag[currentPos]) &&
                   svgTag[currentPos] != '=' && svgTag[currentPos] != '>')
            {
                currentPos++;
            }

            if (currentPos >= end) break;

            string name = svgTag.Substring(nameStart, currentPos - nameStart);
            if (string.IsNullOrEmpty(name)) break;

            // 跳过等号
            while (currentPos < end && char.IsWhiteSpace(svgTag[currentPos]))
            {
                currentPos++;
            }

            if (currentPos >= end || svgTag[currentPos] != '=')
            {
                // 没有值的属性（如 disabled）
                attributes[name] = string.Empty;
                continue;
            }

            currentPos++; // 跳过'='

            // 跳过等号后的空白
            while (currentPos < end && char.IsWhiteSpace(svgTag[currentPos]))
            {
                currentPos++;
            }

            if (currentPos >= end) break;

            // 获取属性值
            char quoteChar = svgTag[currentPos];
            bool isQuoted = quoteChar == '"' || quoteChar == '\'';

            int valueStart = isQuoted ? currentPos + 1 : currentPos;
            int valueEnd;

            if (isQuoted)
            {
                valueEnd = svgTag.IndexOf(quoteChar, valueStart);
                if (valueEnd == -1) break;
            }
            else
            {
                valueEnd = valueStart;
                while (valueEnd < end && !char.IsWhiteSpace(svgTag[valueEnd]) &&
                       svgTag[valueEnd] != '>')
                {
                    valueEnd++;
                }
            }

            if (valueEnd >= end) break;

            string value = isQuoted ?
                svgTag.Substring(valueStart, valueEnd - valueStart) :
                svgTag.Substring(valueStart, valueEnd - valueStart);

            attributes[name] = value;

            currentPos = isQuoted ? valueEnd + 1 : valueEnd;
        }

        return attributes;
    }

}
