using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
namespace WebApiGenerator
{
    public class WebApiGeneratorHepers
    {
        public const string WebControllerAttributeFullName = "WebApiGenerator.Attributes.WebControllerAttribute";

        public static string FormatClassName(string className)
        {
            if (className.IndexOf('`') > -1)
            {
                return className.Substring(0, className.IndexOf('`'));
            }
            return className;
        }

        public static ClassDeclarationSyntax CreateControllerClassDeclaration(GeneratorAttributeSyntaxContext source)
        {
            var cd = ClassDeclaration($"{FormatClassName(source.TargetSymbol.MetadataName)}Controller");
            var classNode = (ClassDeclarationSyntax)source.TargetNode;
            if (classNode is { TypeParameterList: var list and not null })
            {
                cd = cd.AddTypeParameterListParameters([.. list.Parameters]).AddConstraintClauses([.. classNode.ConstraintClauses]);
            }
            cd = cd.AddBaseListTypes(SimpleBaseType(IdentifierName("global::Microsoft.AspNetCore.Mvc.ControllerBase")))
             .AddAttributeLists(AttributeList(SingletonSeparatedList(
                 Attribute(IdentifierName("global::Microsoft.AspNetCore.Mvc.ApiController"))
                 )),
                 AttributeList(SingletonSeparatedList(
                 Attribute(IdentifierName("global::Microsoft.AspNetCore.Mvc.Route")).AddArgumentListArguments(
                     AttributeArgument(LiteralExpression(
                         SyntaxKind.StringLiteralExpression,
                         Literal("api/[controller]/[action]")
                         ))
                     )
                 ))
                 //, AttributeList(SingletonSeparatedList(
                 //    Attribute((IdentifierName("global::Microsoft.AspNetCore.Authorization.Authorize")))
                 //    ))
                 )
             .AddModifiers(Token(TriviaList(Comment("/// <inheritdoc/>")), SyntaxKind.PublicKeyword, TriviaList()))
             .AddMembers(classNode.ChildNodes().Where(n => n is FieldDeclarationSyntax).Cast<FieldDeclarationSyntax>().ToArray());

            return cd;
        }

        public static NamespaceDeclarationSyntax CreateNamespaceDeclaration(GeneratorAttributeSyntaxContext source, out UsingDirectiveSyntax[] usings)
        {
            var np = NamespaceDeclaration(IdentifierName(source.TargetSymbol.ContainingNamespace.ToDisplayString()))
                .WithLeadingTrivia(Comment("// <auto-generated/>"), Trivia(PragmaWarningDirectiveTrivia(Token(SyntaxKind.DisableKeyword), true)));
            //source.TargetSymbol.con
            if (source.TargetNode
                is
                {
                    Parent: NamespaceDeclarationSyntax
                    {
                        Usings: var nu,
                        Parent: CompilationUnitSyntax
                        {
                            Usings: var cnu
                        }
                    }
                }
                )
            {
                usings = [.. nu, .. cnu];
            }
            else
            {
                usings = [];
            }

            return np;
        }
    }



}
