<Project Sdk="Microsoft.NET.Sdk.Razor">
	<Import Project="../../Props/projects.versions.props"/>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>MarvelTiter</Authors>
		<Copyright>MIT</Copyright>
		<Description>BlazorWebAdmin模板项目的组件</Description>
		<Version>$(AppCoreVersion)</Version>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App"></FrameworkReference>
		<!-- OutputItemType="Analyzer" -->
	</ItemGroup>
	
	<ItemGroup Condition="'$(Configuration)'=='DEBUG'">
	  <ProjectReference Include="..\BlazorTemplate.UI.Shared\BlazorTemplate.UI.Shared.csproj" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)'=='RELEASE'">
		<PackageReference Include="BlazorTemplate.UI.Shared" Version="$(SharedProjectVersion)" />
	</ItemGroup>
</Project>

