<Project Sdk="Microsoft.NET.Sdk.Razor">
	<Import Project="../Shared/Props/pack.settings.props" />
	<Import Project="../Shared/Props/projects.versions.props" />
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<RootNamespace>BlazorAdmin.Wpf</RootNamespace>
		<EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
		<InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsNamespaces>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="10.0.90" />
		<PackageReference Include="LightORM.Providers.Sqlite" Version="2026.8.31.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
	</ItemGroup>
	<!--#if(AlwaysFalse)-->
	<ItemGroup>
		<ProjectReference Include="..\Shared\BlazorTemplates\BlazorTemplate.AppServer\BlazorTemplate.AppServer.csproj" />
		<ProjectReference Include="..\Shared\BlazorTemplates\BlazorTemplate.UI.AntBlazor\BlazorTemplate.UI.AntBlazor.csproj" />
	</ItemGroup>
	<!--#endif-->
	<ItemGroup Condition="'$(CurrentMode)'== 'Package'">
		<PackageReference Include="BlazorTemplate.AppServer" Version="$(AppServerVersion)" />
		<PackageReference Include="BlazorTemplate.UI.AntBlazor" Version="$(AntUIVersion)" />
	</ItemGroup>
	<ItemGroup>
	  <Content Update="wpfhost.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

</Project>
