<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<Import Project="../Shared/Props/pack.settings.props" />
	<Import Project="../Shared/Props/projects.versions.props" />
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
		<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
		<Version>$(MainProjectVersion)</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.10" />
	</ItemGroup>
	<!--#if(AlwaysFalse)-->
	<ItemGroup>
	  <ProjectReference Include="..\Shared\BlazorTemplates\BlazorTemplate.UI.AntBlazor\BlazorTemplate.UI.AntBlazor.csproj" />
	  <ProjectReference Include="..\Shared\BlazorTemplates\BlazorTemplate.UI.Shared\BlazorTemplate.UI.Shared.csproj" />
	</ItemGroup>
	<!--#endif-->
	<ItemGroup Condition="'$(CurrentMode)'== 'Package'">
		<PackageReference Include="BlazorTemplate.UI.AntBlazor" Version="$(AntUIVersion)" />
		<PackageReference Include="BlazorTemplate.UI.Shared" Version="$(SharedProjectVersion)" />
	</ItemGroup>

</Project>