using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Linq;
using System.Text;

namespace BlazorTemplate.ClientCore.Generators;

[Generator(LanguageNames.CSharp)]
public class EnumDisplayProviderGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enums = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is EnumDeclarationSyntax,
            static (c, _) =>
            {
                var si = c.SemanticModel.GetDeclaredSymbol(c.Node) as INamedTypeSymbol;
                return si!;
            }
        ).Collect();

        var manual = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is InvocationExpressionSyntax
            {
                Expression: MemberAccessExpressionSyntax { Name.Identifier.Text: "AddEnumLookupProvider" }
            },
            static (c, _) =>
            {
                var invocation = (InvocationExpressionSyntax)c.Node;
                if (c.SemanticModel.GetSymbolInfo(invocation).Symbol is not IMethodSymbol symbol)
                {
                    return null!;
                }
                return (symbol.TypeArguments.FirstOrDefault() as INamedTypeSymbol)!;
            }
            ).Where(t => t is not null).Collect();

        var cc = context.CompilationProvider.Combine(enums.Combine(manual));
        context.RegisterSourceOutput(cc, static (context, c) =>
        {
            var (compilation, enums) = c;
            INamedTypeSymbol[] total = [.. enums.Left, .. enums.Right];
            foreach (var item in total)
            {
                if (!CreateEntries(item, out var contents))
                {
                    continue;
                }
                var fileContent = $$"""
// <auto-generated />
using BlazorTemplate.ClientCore.Lockup;
namespace EnumDisplayProviderGenerator;
public class {{item.Name}}LookupProvider : ILookupProvider
{

    [global::System.Runtime.CompilerServices.ModuleInitializer]
    public static void Init()
    {
        LookupService.AddEnumProvider(new {{item.Name}}LookupProvider());
    }

    private global::System.Collections.Frozen.FrozenDictionary<string, LookupEntry> items;

    public {{item.Name}}LookupProvider()
    {
        var dic = new global::System.Collections.Generic.Dictionary<string, LookupEntry>();
{{contents}}
        items = global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(dic);
    }

    public string TypeName => "{{item.Name}}";

    public string GetDisplayString(string key)
    {
        if (items.TryGetValue(key, out var v) == true)
        {
            return v.DisplayName;
        }
        return key;
    }

    public global::System.Collections.Generic.ICollection<LookupEntry> GetEntries()
    {
        return items.Values;
    }

    public global::System.Collections.Generic.IEnumerable<LookupEntry> LoadData()
    {
        throw new global::System.NotImplementedException();
    }
}
""";
                context.AddSource($"{item.Name}.Enum.g.cs", fileContent);
            }
        });
    }

    private static bool CreateEntries(INamedTypeSymbol enumType, out string content)
    {
        StringBuilder contents = new();
        var fields = enumType.GetMembers().Where(s => s is IFieldSymbol).Cast<IFieldSymbol>().ToArray();
        for (int i = 0; i < fields.Length; i++)
        {
            IFieldSymbol? item = fields[i];
            var code = item.Name;
            var dis = item.GetAttributes().Where(a => a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.DisplayAttribute").FirstOrDefault();
            var label = dis?.NamedArguments.FirstOrDefault(n => n.Key == "Name").Value.Value;
            if (label is null)
            {
                continue;
            }
            contents.AppendLine($"""        var entry{i} = new LookupEntry("{code}", "{label}");""");
            contents.AppendLine($"""        dic.Add("{code}", entry{i});""");
        }
        content = contents.ToString();
        return content.Length > 0;
    }
}
