using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace BlazorTemplate.ClientCore.Generators;

[Generator(LanguageNames.CSharp)]
public class SvgContentClassGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var svgs = context.AdditionalTextsProvider.Where(static file => file.Path.EndsWith(".svg", StringComparison.OrdinalIgnoreCase)).Collect();
        var compilationWithSvgs = context.CompilationProvider.Combine(svgs);
        context.RegisterSourceOutput(compilationWithSvgs, static (context, result) =>
        {
            var (compilation, svgs) = result;
            var a = compilation.Assembly.Name;
            var svgContentClass = new StringBuilder();
            svgContentClass.AppendLine("// <auto-generated />");
            svgContentClass.AppendLine($"namespace {a};");
            svgContentClass.AppendLine("public static class SvgContent");
            svgContentClass.AppendLine("{");

            var svgProviderClass = new StringBuilder();
            svgProviderClass.AppendLine("// <auto-generated />");
            svgProviderClass.AppendLine($"namespace {a};");
            svgProviderClass.AppendLine("public class SvgProvider: global::BlazorTemplate.ClientCore.Services.ISvgIconProvider");
            svgProviderClass.AppendLine("{");
            svgProviderClass.AppendLine("""
                    [global::System.Runtime.CompilerServices.ModuleInitializer]
                    public static void Initialize()
                    {
                        global::BlazorTemplate.ClientCore.DefaultServicesImpl.DefaultSvgIconService.RegisterIcons<SvgProvider>();
                    }
                    
                    public static IEnumerable<global::BlazorTemplate.ClientCore.Services.SvgParsingResult> GetIcons()
                    {
                """);
            foreach (var svg in svgs
            .Select(s => new { Name = Path.GetFileNameWithoutExtension(s.Path), Content = s.GetText()?.ToString() }).Distinct()
            .Where(s => s.Name.StartsWith("svg-") && s.Content is not null))
            {
                //var iconName = Path.GetFileNameWithoutExtension(svg.Path);
                //if (iconName.StartsWith("svg-") == false)
                //{
                //    continue;
                //}
                //var svgContent = svg.GetText()?.ToString();
                //if (svgContent is null)
                //{
                //    continue;
                //}
                var iconName = svg.Name;
                var svgContent = svg.Content!;
                var r = SvgFileParse.Utils.ProcessSvgContent(svgContent);
                var propName = iconName.Replace("-", "_");
                var attributesString = r.Attributes.Count > 0 ? $$"""
                new({{r.Attributes.Count}}) { {{string.Join(", ", r.Attributes.Select(kv => $"{{\"{kv.Key}\", \"{kv.Value}\"}}"))}} }
                """ : "[]";
                svgContentClass.AppendLine($$"""
                        private static Dictionary<string, object> {{propName}}_Attributes { get; } 
                            = {{attributesString}};

                        private static string {{propName}}_InnerContent { get; } 
                            = {{SvgFileParse.Utils.GetRawStringLiteral(r.InnerContent)}};

                        private static string {{propName}}_OriginalContent { get; } 
                            = {{SvgFileParse.Utils.GetRawStringLiteral(r.OriginalContent)}};

                        public static global::BlazorTemplate.ClientCore.Services.SvgParsingResult {{propName}} { get; } 
                            = new("{{iconName}}", {{propName}}_InnerContent, {{propName}}_Attributes, {{propName}}_OriginalContent);

                    """);

                svgProviderClass.AppendLine($"""
                            yield return global::{a}.SvgContent.{propName};
                    """);
            }
            svgContentClass.AppendLine("}");
            if (svgs.Length == 0)
            {
                svgProviderClass.AppendLine("        yield break;");
            }
            svgProviderClass.AppendLine("    }");
            svgProviderClass.AppendLine("}");
            context.AddSource("SvgContent.g.cs", svgContentClass.ToString());
            context.AddSource("SvgProvider.g.cs", svgProviderClass.ToString());
        });
    }
}
