using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BlazorTemplate.ClientCore.Generators;

/// <summary>
/// 把 <see cref="BlazorTemplate.ClientCore.UI.Table.TableColumnContext.GenerateColumns(Type)"/>
/// 里的运行时反射(GetProperties / GetCustomAttribute / Expression.Compile)替换为编译期生成。
///
/// 扫描当前编译单元中带有列相关特性(ColumnDefinition / Display / Form / ColumnTag)的类(含其基类链
/// 以及 [SupplyColumnDefinition] 接口提供定义)，为每个类型生成一段直接构造 ColumnInfo[] 的静态方法，
/// 并通过 ModuleInitializer 注册到 TableColumnContext，运行时不再走反射。
///
/// 反射仍是兜底路径：未被本生成器覆盖的类型(DataRow / Dictionary / 外部程序集类型等)继续走原逻辑。
/// </summary>
[Generator(LanguageNames.CSharp)]
public class TableColumnGenerator : IIncrementalGenerator
{
    private const string ColumnDefinitionAttr = "BlazorTemplate.ClientCore.Common.Attributes.ColumnDefinitionAttribute";
    private const string FormAttr = "BlazorTemplate.ClientCore.Common.Attributes.FormAttribute";
    private const string ColumnTagAttr = "BlazorTemplate.ClientCore.Common.Attributes.ColumnTagAttribute";
    private const string SupplyColumnDefinitionAttr = "BlazorTemplate.ClientCore.Common.Attributes.SupplyColumnDefinitionAttribute";
    private const string LangNameAttr = "BlazorTemplate.ClientCore.Common.Attributes.LangNameAttribute";
    private const string DisplayAttr = "System.ComponentModel.DataAnnotations.DisplayAttribute";

    private const string ColumnInfoFqn = "global::BlazorTemplate.ClientCore.UI.Table.ColumnInfo";
    private const string TableColumnContextFqn = "global::BlazorTemplate.ClientCore.UI.Table.TableColumnContext";
    private const string InputTypeFqn = "global::BlazorTemplate.ClientCore.Common.Attributes.InputType";

    private static readonly SymbolDisplayFormat FqnFormat = SymbolDisplayFormat.FullyQualifiedFormat;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is TypeDeclarationSyntax tds &&
                (tds is ClassDeclarationSyntax or StructDeclarationSyntax or RecordDeclarationSyntax),
            static (c, _) => c.SemanticModel.GetDeclaredSymbol(c.Node) as INamedTypeSymbol)
            .Where(static t => t is not null)
            .Collect();

        context.RegisterSourceOutput(types.Combine(context.CompilationProvider), static (spc, result) =>
        {
            var (types, compilation) = result;
            var header = new StringBuilder();
            var methods = new StringBuilder();
            var usedNames = new HashSet<string>(StringComparer.Ordinal);
            var registrations = new StringBuilder();
            int generated = 0;
            foreach (var type in types)
            {
                if (type is null) continue;
                if (!EqualityComparer<IAssemblySymbol>.Default.Equals(type.ContainingAssembly, compilation.Assembly)) continue;
                if (type.TypeParameters.Length > 0) continue;      // 开放泛型交给反射兜底
                if (type.IsStatic) continue;

                var columns = CollectColumns(type);
                if (columns.Count == 0) continue;

                var methodName = UniqueName("Build_" + Sanitize(type.Name), usedNames);
                registrations.AppendLine($"        {TableColumnContextFqn}.RegisterGeneratedColumns(typeof({Fqn(type)}), static () => {methodName}());");

                methods.AppendLine($$"""
                        private static {{ColumnInfoFqn}}[] {{methodName}}()
                        {
                            var list = new global::System.Collections.Generic.List<{{ColumnInfoFqn}}>();
                    """);
                for (int i = 0; i < columns.Count; i++)
                {
                    EmitColumn(methods, type, columns[i], i);
                }
                methods.AppendLine("""
                            return list.ToArray();
                        }
                    """);
                generated++;
            }

            if (generated == 0)
            {
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {compilation.Assembly.Name};");
            sb.AppendLine();
            sb.AppendLine("public static class TableColumnRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("    public static void Initialize()");
            sb.AppendLine("    {");
            sb.Append(registrations);
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.Append(methods);
            sb.AppendLine("}");

            spc.AddSource("TableColumnRegistry.g.cs", sb.ToString());
        });
    }

    // ---------------------------------------------------------------------
    // 列收集(与 TableColumnContext.GenerateColumns 的反射语义保持一致)
    // ---------------------------------------------------------------------

    private static List<ColumnModel> CollectColumns(INamedTypeSymbol type)
    {
        var props = GetPublicInstanceProperties(type);
        var interfaceProps = GetSupplyInterfaceProps(type).ToList();
        string? upperLang = GetLangNameFromInterfaces(type);

        var columns = new List<ColumnModel>();
        foreach (var prop in props)
        {
            IPropertySymbol? upper = interfaceProps.FirstOrDefault(p => p.Name == prop.Name);
            if (!TryBuildColumn(prop, upper, upperLang, out var column))
            {
                continue;
            }
            column.ColumnIndex = columns.Count;
            columns.Add(column);
        }

        if (columns.Any(c => c.Index != 0))
        {
            // 反射用的是 List.Sort(不稳定排序)；这里在编译期用稳定排序，等价且更确定。
            columns = [.. columns.OrderBy(c => c.Index)];
        }
        return columns;
    }

    /// <summary>按反射 GetProperties() 的顺序返回公共实例属性：派生类先、基类后，同类内按声明顺序。</summary>
    private static IEnumerable<IPropertySymbol> GetPublicInstanceProperties(INamedTypeSymbol type)
    {
        for (var t = type; t is not null && t.SpecialType != SpecialType.System_Object; t = t.BaseType)
        {
            foreach (var m in t.GetMembers())
            {
                if (m is IPropertySymbol p
                    && p.DeclaredAccessibility == Accessibility.Public
                    && !p.IsStatic
                    && !p.IsIndexer
                    && p.ExplicitInterfaceImplementations.Length == 0)
                {
                    yield return p;
                }
            }
        }
    }

    /// <summary>带 [SupplyColumnDefinition] 的接口上声明的公共实例属性。</summary>
    private static IEnumerable<IPropertySymbol> GetSupplyInterfaceProps(INamedTypeSymbol type)
    {
        foreach (var iface in type.AllInterfaces)
        {
            if (!HasAttribute(iface, SupplyColumnDefinitionAttr))
            {
                continue;
            }
            foreach (var m in iface.GetMembers())
            {
                if (m is IPropertySymbol p
                    && p.DeclaredAccessibility == Accessibility.Public
                    && !p.IsStatic
                    && !p.IsIndexer
                    && p.ExplicitInterfaceImplementations.Length == 0)
                {
                    yield return p;
                }
            }
        }
    }

    private static string? GetLangNameFromInterfaces(INamedTypeSymbol type)
    {
        foreach (var iface in type.AllInterfaces)
        {
            var lang = GetLangName(iface);
            if (lang is not null)
            {
                return lang;
            }
        }
        return null;
    }

    private static bool TryBuildColumn(IPropertySymbol self, IPropertySymbol? upper, string? upperLang, out ColumnModel column)
    {
        var col = GetAttribute(self, ColumnDefinitionAttr) ?? GetAttribute(upper, ColumnDefinitionAttr);
        var display = GetAttribute(self, DisplayAttr) ?? GetAttribute(upper, DisplayAttr);
        var form = GetAttribute(self, FormAttr) ?? GetAttribute(upper, FormAttr);

        var model = new ColumnModel
        {
            Property = self,
            Visible = true,
            Searchable = true,
            ShowOnForm = true,
        };

        if (col is not null)
        {
            ReadColumnDefinition(col, model);
        }
        else if (display is not null)
        {
            model.Label = NamedString(display, "Name") ?? string.Empty;
            model.LabelIsResolved = !string.IsNullOrEmpty(model.Label);
        }
        else if (form is not null)
        {
            model.Visible = false;
        }
        else
        {
            column = null!;
            return false;
        }

        // 标签兜底：head.Label == null 时用 LangName / 类型名拼接
        if (model.LabelIsResolved is false || string.IsNullOrEmpty(model.Label))
        {
            var lang = GetLangName(self.ContainingType) ?? GetLangName(upper?.ContainingType) ?? upperLang;
            model.Label = lang is not null ? $"{lang}.{self.Name}" : $"{self.ContainingType.Name}.{self.Name}";
            model.LabelIsResolved = true;
        }

        // Form 覆盖
        if (form is not null)
        {
            ReadForm(form, model);
        }

        // ColumnTag 颜色
        var tagAttrs = GetAttributes(self, ColumnTagAttr).Concat(GetAttributes(upper, ColumnTagAttr));
        var tags = new List<(string Value, string Color)>();
        foreach (var t in tagAttrs)
        {
            if (t is null)
            {
                continue;
            }
            tags.Add(ReadColumnTag(t));
        }
        if (tags.Count > 0)
        {
            model.UseTag = true;
            // 与反射 TryAdd 一致：同名取第一个
            model.TagColors = tags.GroupBy(x => x.Value).Select(g => g.First()).ToList();
        }

        model.CanSet = CanEmitSetter(self);
        column = model;
        return true;
    }

    // ---------------------------------------------------------------------
    // 特性读取
    // ---------------------------------------------------------------------

    private static AttributeData? GetAttribute(ISymbol? symbol, string fqn)
    {
        if (symbol is null)
        {
            return null;
        }
        foreach (var a in symbol.GetAttributes())
        {
            if (a.AttributeClass?.ToDisplayString() == fqn)
            {
                return a;
            }
        }
        return null;
    }

    private static IEnumerable<AttributeData?> GetAttributes(ISymbol? symbol, string fqn)
    {
        if (symbol is null)
        {
            yield break;
        }
        foreach (var a in symbol.GetAttributes())
        {
            if (a.AttributeClass?.ToDisplayString() == fqn)
            {
                yield return a;
            }
        }
    }

    private static bool HasAttribute(ISymbol symbol, string fqn)
        => symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == fqn);

    private static string? GetLangName(ISymbol? symbol)
    {
        var attr = GetAttribute(symbol, LangNameAttr);
        if (attr is null)
        {
            return null;
        }
        for (int i = 0; i < attr.ConstructorArguments.Length; i++)
        {
            if (attr.AttributeConstructor!.Parameters[i].Name == "name" && !attr.ConstructorArguments[i].IsNull)
            {
                return attr.ConstructorArguments[i].Value as string;
            }
        }
        return null;
    }

    private static void ReadColumnDefinition(AttributeData a, ColumnModel m)
    {
        // 构造参数：label / sort / fix / width(两个构造器都按参数名对齐)
        for (int i = 0; i < a.ConstructorArguments.Length; i++)
        {
            var name = a.AttributeConstructor!.Parameters[i].Name;
            var val = a.ConstructorArguments[i];
            switch (name)
            {
                case "label":
                    if (!val.IsNull)
                    {
                        m.Label = (string?)val.Value ?? string.Empty;
                        m.LabelIsResolved = true;
                    }
                    break;
                case "sort":
                    m.Index = val.IsNull ? 0 : (int)val.Value!;
                    break;
                case "fix":
                    m.Fixed = val.IsNull ? null : (string?)val.Value;
                    break;
                case "width":
                    m.Width = val.IsNull ? null : (string?)val.Value;
                    break;
            }
        }
        // 可写属性(named arguments)
        foreach (var kv in a.NamedArguments)
        {
            switch (kv.Key)
            {
                case "Label":
                    m.Label = kv.Value.IsNull ? string.Empty : (string?)kv.Value.Value ?? string.Empty;
                    m.LabelIsResolved = !string.IsNullOrEmpty(m.Label);
                    break;
                case "Align":
                    m.Align = kv.Value.IsNull ? null : (string?)kv.Value.Value;
                    break;
                case "UseTag":
                    m.UseTag = !kv.Value.IsNull && (bool)kv.Value.Value!;
                    break;
                case "Readonly":
                    m.Readonly = !kv.Value.IsNull && (bool)kv.Value.Value!;
                    break;
                case "Visible":
                    m.Visible = kv.Value.IsNull || (bool)kv.Value.Value!;
                    break;
                case "Ellipsis":
                    m.Ellipsis = !kv.Value.IsNull && (bool)kv.Value.Value!;
                    break;
                case "Format":
                    m.Format = kv.Value.IsNull ? null : (string?)kv.Value.Value;
                    break;
                case "Searchable":
                    m.Searchable = kv.Value.IsNull || (bool)kv.Value.Value!;
                    break;
                case "Editable":
                    m.Editable = !kv.Value.IsNull && (bool)kv.Value.Value!;
                    break;
                case "Sortable":
                    m.Sortable = !kv.Value.IsNull && (bool)kv.Value.Value!;
                    break;
            }
        }
    }

    private static void ReadForm(AttributeData a, ColumnModel m)
    {
        int row = 0;
        int column = 0;
        bool hide = false;
        string? label = null;
        string? inputType = null;

        for (int i = 0; i < a.ConstructorArguments.Length; i++)
        {
            if (a.AttributeConstructor!.Parameters[i].Name == "inputType" && !a.ConstructorArguments[i].IsNull)
            {
                inputType = EnumMemberName(a.ConstructorArguments[i]);
            }
        }
        foreach (var kv in a.NamedArguments)
        {
            switch (kv.Key)
            {
                case "Row":
                    row = kv.Value.IsNull ? 0 : (int)kv.Value.Value!;
                    break;
                case "Column":
                    column = kv.Value.IsNull ? 0 : (int)kv.Value.Value!;
                    break;
                case "Hide":
                    hide = !kv.Value.IsNull && (bool)kv.Value.Value!;
                    break;
                case "Label":
                    label = kv.Value.IsNull ? null : (string?)kv.Value.Value;
                    break;
                case "InputType":
                    inputType = kv.Value.IsNull ? null : EnumMemberName(kv.Value);
                    break;
            }
        }

        m.Row = row;
        m.Column = column;
        m.ShowOnForm = !hide;
        m.InputType = inputType;
        if (!string.IsNullOrEmpty(label))
        {
            m.Label = label!;
            m.LabelIsResolved = true;
        }
    }

    private static (string Value, string Color) ReadColumnTag(AttributeData a)
    {
        string value = string.Empty;
        string color = string.Empty;

        for (int i = 0; i < a.ConstructorArguments.Length; i++)
        {
            var name = a.AttributeConstructor!.Parameters[i].Name;
            var val = a.ConstructorArguments[i];
            if (name == "color")
            {
                color = val.IsNull ? string.Empty : (string?)val.Value ?? string.Empty;
            }
            else if (name == "formattedValue")
            {
                value = ComputeTagValue(val);
            }
        }
        foreach (var kv in a.NamedArguments)
        {
            if (kv.Key == "Color")
            {
                color = kv.Value.IsNull ? string.Empty : (string?)kv.Value.Value ?? string.Empty;
            }
            else if (kv.Key == "Value")
            {
                value = kv.Value.IsNull ? string.Empty : (string?)kv.Value.Value ?? string.Empty;
            }
        }
        return (value, color);
    }

    private static string ComputeTagValue(TypedConstant tc)
    {
        if (tc.IsNull)
        {
            return string.Empty;
        }
        return tc.Kind switch
        {
            TypedConstantKind.Enum => EnumMemberName(tc) ?? tc.Value?.ToString() ?? string.Empty,
            TypedConstantKind.Primitive => tc.Value?.ToString() ?? string.Empty,
            _ => string.Empty,
        };
    }

    /// <summary>
    /// 取枚举常量对应的成员名。注意：同编译单元内的源码枚举，TypedConstant.Value 可能是底层数值
    /// (如 Int32)而非 IFieldSymbol，需要从枚举类型反查成员名。
    /// </summary>
    private static string? EnumMemberName(TypedConstant tc)
    {
        if (tc.Kind != TypedConstantKind.Enum || tc.Value is null)
        {
            return null;
        }
        if (tc.Value is IFieldSymbol field)
        {
            return field.Name;
        }
        if (tc.Type is INamedTypeSymbol enumType)
        {
            foreach (var m in enumType.GetMembers())
            {
                if (m is IFieldSymbol f && f.HasConstantValue && f.ConstantValue is not null && f.ConstantValue.Equals(tc.Value))
                {
                    return f.Name;
                }
            }
        }
        return tc.Value.ToString();
    }

    private static string? NamedString(AttributeData a, string key)
    {
        foreach (var kv in a.NamedArguments)
        {
            if (kv.Key == key)
            {
                return kv.Value.IsNull ? null : (string?)kv.Value.Value;
            }
        }
        return null;
    }

    /// <summary>只有可访问的 setter 才生成赋值委托；init-only / 无 setter / 跨程序集私有 setter 不生成。</summary>
    private static bool CanEmitSetter(IPropertySymbol p)
    {
        var set = p.SetMethod;
        if (set is null || set.IsInitOnly)
        {
            return false;
        }
        return set.DeclaredAccessibility switch
        {
            Accessibility.Public => true,
            // internal / protected internal 只有在同程序集(源码类型)才可访问
            Accessibility.Internal or Accessibility.ProtectedOrInternal => p.ContainingType.DeclaringSyntaxReferences.Length > 0,
            _ => false,
        };
    }

    // ---------------------------------------------------------------------
    // 代码生成
    // ---------------------------------------------------------------------

    private static void EmitColumn(StringBuilder sb, INamedTypeSymbol type, ColumnModel m, int index)
    {
        var varName = $"c{index}";
        var dataType = Fqn(m.Property.Type);
        var castType = Fqn(m.Property.ContainingType);
        var propName = m.Property.Name;
        var tagColors = m.TagColors is null ? "null" : $$"""
new global::System.Collections.Generic.Dictionary<string, string> 
            { 
                {{string.Join(", ", m.TagColors.Select(tc => $"[{Literal(tc.Value)}] = {Literal(tc.Color)}"))}}
            }
""";
        var getter = $"static (object o) => (({castType})o).{propName}!";
        var setter = m.CanSet ? $"static (object o, object v) => (({castType})o).{propName} = ({dataType})v" : "null";
        sb.AppendLine($$"""
        var {{varName}} = new {{ColumnInfoFqn}}({{Literal(m.Label)}}, {{Literal(propName)}}, typeof({{dataType}}))
        {
            Index = {{m.Index}},
            Fixed = {{LiteralOrNull(m.Fixed)}},
            Width = {{LiteralOrNull(m.Width)}},
            Align = {{LiteralOrNull(m.Align)}},
            Visible = {{Bool(m.Visible)}},
            Ellipsis = {{Bool(m.Ellipsis)}},
            Readonly = {{Bool(m.Readonly)}},
            UseTag = {{Bool(m.UseTag)}},
            Sortable = {{Bool(m.Sortable)}},
            Format = {{LiteralOrNull(m.Format)}},
            Searchable = {{Bool(m.Searchable)}},
            Editable = {{Bool(m.Editable)}},
            Row = {{NumOrNull(m.Row)}},
            Column = {{NumOrNull(m.Column)}},
            ShowOnForm = {{Bool(m.ShowOnForm)}},
            InputType = {{EnumOrNull(m.InputType)}},
            TagColors = {{tagColors}},
        };
        {{varName}}.ColumnIndex = {{m.ColumnIndex}};
        {{varName}}.SetAccessors({{getter}}, {{setter}});
        list.Add({{varName}});
""");
    }

    private static string Fqn(ITypeSymbol t) => t.ToDisplayString(FqnFormat);

    private static string Bool(bool b) => b ? "true" : "false";

    private static string NumOrNull(int? n) => n is null ? "null" : n.Value.ToString();

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string LiteralOrNull(string? value) => value is null ? "null" : Literal(value);

    private static string EnumOrNull(string? member)
        => member is null ? "null" : $"{InputTypeFqn}.{member}";

    private static string Sanitize(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
        {
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }
        return sb.ToString();
    }

    private static string UniqueName(string baseName, HashSet<string> used)
    {
        var name = baseName;
        int i = 1;
        while (!used.Add(name))
        {
            name = baseName + "_" + i++;
        }
        return name;
    }

    private sealed class ColumnModel
    {
        public IPropertySymbol Property = null!;
        public string Label = string.Empty;
        public bool LabelIsResolved;
        public int Index;
        public int ColumnIndex;
        public string? Fixed;
        public string? Width;
        public string? Align;
        public bool Visible = true;
        public bool Ellipsis;
        public bool Readonly;
        public bool UseTag;
        public bool Sortable;
        public string? Format;
        public bool Searchable = true;
        public bool Editable;
        public int? Row;
        public int? Column;
        public bool ShowOnForm = true;
        public string? InputType;
        public List<(string Value, string Color)>? TagColors;
        public bool CanSet;
    }
}
