name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Create local NuGet source
        run:
          |
          mkdir -p $HOME/.local-nuget
          dotnet nuget add source $HOME/.local-nuget --name local

      - name: Pack BlazorTemplate.ClientCore
        run: |
          dotnet build src/Shared/BlazorTemplates/SvgContentClassGenerator/SvgContentClassGenerator.csproj -c Release    
          dotnet build src/Shared/BlazorTemplates/EnumDisplayProviderGenerator/EnumDisplayProviderGenerator.csproj -c Release    
          dotnet build src/Shared/BlazorTemplates/BlazorTemplate.ClientCore/BlazorTemplate.ClientCore.csproj -c Release         
          dotnet pack --no-build -c Release src/Shared/BlazorTemplates/BlazorTemplate.ClientCore/BlazorTemplate.ClientCore.csproj -o $HOME/.local-nuget

      - name: Pack BlazorTemplate.AppServer
        run: |
          dotnet build src/Shared/BlazorTemplates/BlazorTemplate.AppServer/BlazorTemplate.AppServer.csproj -c Release
          dotnet pack --no-build -c Release src/Shared/BlazorTemplates/BlazorTemplate.AppServer/BlazorTemplate.AppServer.csproj -o $HOME/.local-nuget

      - name: Pack BlazorTemplate.UI.AntBlazor
        run: |
          dotnet build src/Shared/BlazorTemplates/BlazorTemplate.UI.AntBlazor/BlazorTemplate.UI.AntBlazor.csproj -c Release
          dotnet pack --no-build -c Release src/Shared/BlazorTemplates/BlazorTemplate.UI.AntBlazor/BlazorTemplate.UI.AntBlazor.csproj -o $HOME/.local-nuget

      - name: Pack BlazorTemplate.UI.FluentUI
        run: |
          dotnet build src/Shared/BlazorTemplates/BlazorTemplate.UI.FluentUI/BlazorTemplate.UI.FluentUI.csproj -c Release
          dotnet pack --no-build -c Release src/Shared/BlazorTemplates/BlazorTemplate.UI.FluentUI/BlazorTemplate.UI.FluentUI.csproj -o $HOME/.local-nuget

      - name: Pack Template
        run: |
          dotnet build template.csproj -c Release
          dotnet pack --no-build -c Release template.csproj -o $HOME/.local-nuget

      - name: Publish NuGet packages
        run: dotnet nuget push $HOME/.local-nuget/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
