<Project>
	<PropertyGroup>
		<MainProjectVersion>2026.08.05.1</MainProjectVersion>
        <AppCoreVersion>2026.08.05.1</AppCoreVersion>
        <ConstraintsVersion>2026.08.10.2</ConstraintsVersion>
        <AntUIVersion>2026.08.05.1</AntUIVersion>
        <SharedProjectVersion>2026.08.05.1</SharedProjectVersion>
        <FluentUIVersion>2026.08.05.1</FluentUIVersion>
	</PropertyGroup>
</Project>
