<Project>
	<PropertyGroup>
		<MainProjectVersion>2026.08.26.1-pre</MainProjectVersion>
        <AppServerVersion>2026.08.26.1-pre</AppServerVersion>
        <ClientCoreVersion>2026.08.26.1-pre</ClientCoreVersion>
        <AntUIVersion>2026.08.26.1-pre</AntUIVersion>
        <FluentUIVersion>2026.08.26.1-pre</FluentUIVersion>
	</PropertyGroup>
</Project>
